name: task_manager_app
description: Task Tuner

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.48+28

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  get: ^5.0.0-beta.52
  # get:
  #   path: 
  #     ../getx
  nsg_data:
    path: 
      ../nsg_data
  nsg_controls:
    path: 
      ../nsg_controls

  intl: ^0.17.0
  flutter_svg: ^2.0.2
  simple_shadow: ^0.3.0
  flutter_slidable: ^1.2.0
  slidable_button: ^1.3.1
  flutter_fadein: ^2.0.0
  jiffy: ^5.0.0
  image_picker: ^0.8.5+3
  image_picker_windows: ^0.1.0+2
  file_selector: ^0.8.2+1
  file_selector_windows: ^0.8.2
  file_selector_linux: ^0.9.0+1
  image_picker_for_web: ^2.1.8
  file_picker: ^5.0.1
  flutter_switch: ^0.3.2
  adaptive_scrollbar: ^2.1.2
  scroll_navigation: ^1.3.2
  # html_editor_enhanced: ^2.5.1
  flutter_quill: ^6.4.2
  # flutter_quill_extensions: ^0.1.0
  flutter_markdown: ^0.6.14
  # markdown_editable_textinput: ^2.2.0
   # слайдер
  carousel_slider: ^4.2.1
  path: ^1.8.1
  percent_indicator: ^4.0.1
  mask_text_input_formatter: ^2.3.0
  flutter_multi_formatter: ^2.6.2
  hovering: ^1.0.4
  video_player_win: ^2.2.0
  video_player: ^2.6.0
  url_launcher: ^6.1.10
  firebase_analytics: ^10.1.0
  firebase_core: ^2.4.1
  flutter_reorderable_grid_view: ^3.1.3
  dio: ^4.0.6
  responsive_grid: ^2.1.0
  substring_highlight: ^1.0.33

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

  #flutter_launcher_icons: ^0.11.0

flutter_icons:
  ios: true
  remove_alpha_ios: true
  image_path_ios: C:\Users\Acer\Private\Work\NSG_software\Brand_identity\Apps_licons\Apps_licons_png\task_manager_app_icon_colored_1024х1024.png
  web:
    generate: true
    image_path: C:\Users\Acer\Private\Work\NSG_software\Brand_identity\Apps_licons\Apps_licons_png\task_manager_app_icon_colored_192х192.png
  windows:
    generate: true
    image_path: C:\Users\Acer\Private\Work\NSG_software\Brand_identity\Apps_licons\Apps_licons_png\task_manager_app_icon_colored_256х256.png
    icon_size: 256
  macos:
    generate: true
    image_path: C:\Users\Acer\Private\Work\NSG_software\Brand_identity\Apps_licons\Apps_licons_png\task_manager_app_icon_colored_1024х1024.png

flutter:
  uses-material-design: true
  assets:
    - lib/assets/
    - lib/assets/images/
    - lib/assets/close-48.png
  fonts:
    - family: Inter
      fonts:
        - asset: lib/assets/fonts/Inter-Medium.ttf

    - family: NotoSans
      fonts:
        - asset: lib/assets/fonts/NotoSans-Regular.ttf
